name: Deploy EC2 and Update Kubectl

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    name: Deploy to EC2 and Update Kubectl
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1 
      - name: Get EC2 instance ID by name
        id: get-instance-id
        run: |
          instance_id=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=your-instance-name" --query "Reservations[].Instances[].InstanceId" --output text)
          echo "::set-output name=instance_id::$instance_id"
  
      - name: Get EC2 instance information
        id: ec2-info
        run: |
          instance_info=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=your-instance-name")
          echo "::set-output name=instance_info::$instance_info"

      - name: Extract host from instance information
        id: extract-host
        run: |
          instance_info="${{ steps.ec2-info.outputs.instance_info }}"
          echo "instance_info ->> $instance_info"
          host=$(echo "$instance_info" | jq -r '.Reservations[0].Instances[0].PublicIpAddress')
          echo "::set-output name=host::$host"
          
      - name: Apply role to EC2 instance
        run: |
          instance_id="${{ steps.get-instance-id.outputs.instance_id }}"
          aws ec2 associate-iam-instance-profile --iam-instance-profile Name=ed-eks-worker-new-profile --instance-id $instance_id
      
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          host: $host
          username: "ec2-user"
          script: |
            echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
            curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.29.0/2024-01-04/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
            echo 'export PATH=$HOME/bin:$PATH' >> ~/.bash_profile
            
            aws eks update-kubeconfig --region us-east-1 --name restaurant-34
