name: Deploy EC2 and Update Kubectl

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - name: Install Kubernetes
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          host: "52.87.247.252"
          username: "ec2-user"
          script: |
            curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.29.0/2024-01-04/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
            echo 'export PATH=$HOME/bin:$PATH' >> ~/.bash_profile
            
            echo "export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}" >> ~/.bash_profile
            echo "export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY }}" >> ~/.bash_profile
            echo 'export AWS_DEFAULT_REGION=us-east-1' >> ~/.bash_profile

      - name: Set Credentials
        uses: aws-actions/configure-aws-cli@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - name: Login AWS
        run: |
          aws sts get-caller-identity
      - name: Configure EKS
        run: |
            aws eks update-kubeconfig --region us-east-1 --name restaurant-34
