# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        with:
            key: ${{ secrets.AWS_PRIVATE_KEY }}
            host: "34.239.121.43"
            username: "ec2-user"
      
            script: |
              curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.29.0/2024-01-04/bin/linux/amd64/kubectl
              chmod +x ./kubectl
              mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
              echo 'export PATH=$HOME/bin:$PATH' >> ~/.bash_profile
              
              aws --version
              aws configure set aws_access_key_id $AWS_SECRET_KEY
              aws configure set aws_secret_access_key $AWS_ACCESS_KEY
              aws configure set region us-east-1
              
              aws sts get-caller-identity
              aws eks update-kubeconfig --region us-east-1 --name restaurant-34

      
