name: Deploy EC2 and Update Kubectl

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_PRIVATE_KEY }}

      - name: Transfer script to EC2
        run: scp -o StrictHostKeyChecking=no -i ${{ secrets.AWS_PRIVATE_KEY }} scripts/install_kubernetes.sh ec2-user@52.87.247.252:/tmp/
  
      - name: Execute script on EC2
        run: ssh -o StrictHostKeyChecking=no -i ${{ secrets.AWS_PRIVATE_KEY }} ec2-user@52.87.247.252 'bash /tmp/install_kubernetes.sh'
