name: Deploy EC2 and Update Kubectl

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    name: Deploy to EC2 and Update Kubectl
    runs-on: ubuntu-latest
    
    steps:
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          host: "18.207.215.116"
          username: "ec2-user"
          script: |
            echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
            curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.29.0/2024-01-04/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
            echo 'export PATH=$HOME/bin:$PATH' >> ~/.bash_profile
            
            aws eks update-kubeconfig --region us-east-1 --name restaurant-34
